baseURL = 'https://www.davidstraub.de/'
languageCode = 'en-us'
title = 'David Straub'
theme = 'hugo-book'
disableKinds = ['taxonomy']
[params]
  BookTheme = 'auto'
  BookSection = '*'
  BookComments = false
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
